### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by KadekM** [Tzbob/scalatags-vdom#1]
I have forked your project and am pushing it a bit more at https://github.com/KadekM/scalatags-vdom... I'd appreciate if you'd specify licensing for it.

Great job by the way :+1:

**Comment by tzbob** [comment]
I added the MIT license. I'm currently using this library in a personal project so maintenance is kind of flaky. I'll gladly accept most pull-requests that don't break (too much) ;).

**Comment by KadekM** [comment]
Thanks, maybe once I have it in more consistent state... I have added hooks to vdom, so you can add event handlers like `onclick`...
